// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxHXFBVaZC_Z9IHCmTozjc3tCucP3UUPw',
    appId: '1:889118773572:web:202af9a2f7a04e0c85c711',
    messagingSenderId: '889118773572',
    projectId: 'stylish-23f54',
    authDomain: 'stylish-23f54.firebaseapp.com',
    storageBucket: 'stylish-23f54.appspot.com',
    measurementId: 'G-3VLCLCJQQR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDZ54Uq-gVCaMDk0Hevnvvb7hvWQyQDws',
    appId: '1:889118773572:android:affec74d92b1195d85c711',
    messagingSenderId: '889118773572',
    projectId: 'stylish-23f54',
    storageBucket: 'stylish-23f54.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe5QuL_pWaUJpEBW804vPUpVYRtWb22vw',
    appId: '1:889118773572:ios:c770761bedb0dba085c711',
    messagingSenderId: '889118773572',
    projectId: 'stylish-23f54',
    storageBucket: 'stylish-23f54.appspot.com',
    iosBundleId: 'com.example.stylehub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCe5QuL_pWaUJpEBW804vPUpVYRtWb22vw',
    appId: '1:889118773572:ios:822d4f89d5dc5e5f85c711',
    messagingSenderId: '889118773572',
    projectId: 'stylish-23f54',
    storageBucket: 'stylish-23f54.appspot.com',
    iosBundleId: 'com.example.stylehub.RunnerTests',
  );
}
